{% set name = "pyro-ppl" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8ec6968fdfa34f140584b266099238f1ffeacbbaab3775de5c94c0e685d018a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.7
    - opt_einsum >=2.3.2
    - pyro-api >=0.1.1
    - python >=3.6
    - pytorch >=1.8
    - tqdm >=4.36

test:
  imports:
    - pyro
    - pyro.contrib
    - pyro.distributions
    - pyro.infer
    - pyro.nn
    - pyro.ops
    - pyro.optim
    - pyro.params
    - pyro.poutine

about:
  home: http://pyro.ai
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.md
  summary: A Python library for probabilistic modeling and inference
  doc_url: https://docs.pyro.ai/
  dev_url: https://github.com/pyro-ppl/pyro/

extra:
  recipe-maintainers:
    - jamestwebber
